server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: movie
          uri: http://localhost:8081
          predicates:
            - Path=/movies/** 
        - id: theater
          uri: http://localhost:8082
          predicates:
            - Path=/theaters/** 
        - id: booking
          uri: http://localhost:8083
          predicates:
            - Path=/bookings/** 
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/notificationHistories/** 
        - id: payment
          uri: http://localhost:8085
          predicates:
            - Path=/paymentHistories/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: movie
          uri: http://movie:8080
          predicates:
            - Path=/movies/** 
        - id: theater
          uri: http://theater:8080
          predicates:
            - Path=/theaters/** 
        - id: booking
          uri: http://booking:8080
          predicates:
            - Path=/bookings/** 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notificationHistories/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/paymentHistories/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
